version: '3.3'
services:
  sso-service:
    environment:
      - DB_PORT:${DB_PORT}
      - DB_CONNECTION:${DB_CONNECTION}
      - DB_HOST:${DB_HOST}
      - DB_USER:${DB_USER}
      - DB_PASS:${DB_PASS}
      - DB_NAME:${DB_NAME}
      - JWT_SECRET:${JWT_SECRET}
      - JWT_EXPIRED:${JWT_EXPIRED}
      - JWT_REFRESH_TOKEN_EXPIRED:${JWT_REFRESH_TOKEN_EXPIRED}
      - REDIS_EXPIRE_ACCESS_TOKEN:${REDIS_EXPIRE_ACCESS_TOKEN}
      - REDIS_EXPIRE_REFRESH_TOKEN:${REDIS_EXPIRE_REFRESH_TOKEN}
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3344:3344'